version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
